### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mmofid** [BinaryTENSHi/ChenTelegramApi#3]
Hi BinaryTENSHi
I compile your project but i dont know how to use your project for send and receive with Telegram.
do you sample code for using your project.

Best Regards

**Comment by BinaryTENSHi** [comment]
The library itself is not fully implemented yet.

It's a free-time project, so I work very little on it.
I hope I can find some time to devote to this project.

When it reaches a somewhat mature status, I'll make sure to provide a proper documentation and samples.
