### ISSUE TITLE
How to work with The TelegramApi

### ISSUE THREAD

**Issue by Ansel1990B** [BinaryTENSHi/ChenTelegramApi#4]
How do I use this Api?

**Comment by BinaryTENSHi** [comment]
The library itself is not fully implemented yet.

As you may have seen, I haven't worked on this project for almost a year.
In the future, I hope I can find more time to devote to this project.

When it reaches a somewhat mature status, I'll make sure to provide a proper documentation and samples.

**Comment by Ansel1990B** [comment]
I can help you to complete the library

When can we start working?
